name = "host-markupsafe"
version = "3.0.3"
kind = "host"
build_system = "special"
special = "host-python-module"
dependencies = ["host-python"]
environment = ["PYTHON_MODULE=markupsafe", "PYTHON_SOURCE=src/markupsafe"]

[source]
url = "https://files.pythonhosted.org/packages/7e/99/7690b6d4034fffd95959cbe0c02de8deb3098cc577c67bb6a24fe5d7caa7/markupsafe-{version}.tar.gz"
sha256 = "722695808f4b6457b320fdc131280796bdceb04ab50fe1795cd540799ebe1698"
