name = "dosfstools"
version = "4.2"
kind = "target"
build_system = "autotools"
dependencies = []

[source]
url = "https://github.com/dosfstools/dosfstools/releases/download/v{version}/dosfstools-{version}.tar.gz"
