name = "ttyd"
version = "1.7.7"
kind = "target"
build_system = "cmake"
dependencies = ["json-c", "libuv", "libwebsockets", "openssl", "zlib"]
configure_args = []

[source]
url = "https://github.com/tsl0922/ttyd/archive/refs/tags/{version}.tar.gz"
sha256 = "039dd995229377caee919898b7bd54484accec3bba49c118e2d5cd6ec51e3650"
