name = "flatpak"
version = "1.16.1"
kind = "target"
build_system = "meson"
dependencies = ["host-pyparsing", "appstream", "bubblewrap", "dbus", "fuse3", "gdk-pixbuf", "json-glib", "libarchive", "libcap", "curl", "glib", "libostree", "libsoup", "libseccomp", "libxml2", "xdg-dbus-proxy", "xz", "zstd"]
configure_args = ["-Dauto_sideloading=false", "-Ddconf=disabled", "-Ddocbook_docs=disabled", "-Dgir=disabled", "-Dgtkdoc=disabled", "-Dinstalled_tests=false", "-Dinternal_checks=false", "-Dlibzstd=enabled", "-Dmalcontent=disabled", "-Dman=disabled", "-Dsandboxed_triggers=true", "-Dseccomp=enabled", "-Dselinux_module=disabled", "-Dsystem_bubblewrap=/usr/bin/bwrap", "-Dsystem_dbus_proxy=/usr/bin/xdg-dbus-proxy", "-Dsystem_fusermount=/usr/bin/fusermount3", "-Dsystem_helper=disabled", "-Dsystem_install_dir=/var/lib/flatpak", "-Dsystemd=disabled", "-Dtests=false", "-Dwayland_security_context=disabled", "-Dxauth=disabled"]
patches = ["flatpak-cross-bwrap-check.patch"]

[source]
url = "https://github.com/flatpak/flatpak/releases/download/{version}/flatpak-{version}.tar.xz"
