name = "dbus"
version = "1.16.2"
kind = "target"
build_system = "meson"
dependencies = ["expat"]
configure_args = ["-Dsystemd=disabled", "-Dselinux=disabled", "-Dapparmor=disabled", "-Dlibaudit=disabled", "-Dintrusive_tests=false", "-Dmodular_tests=disabled", "-Dinstalled_tests=false", "-Dtools=true", "-Dxml_docs=disabled", "-Ddoxygen_docs=disabled", "-Dducktype_docs=disabled", "-Dx11_autolaunch=disabled"]

[source]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-{version}.tar.xz"
sha256 = "0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"
