name = "libxmlb"
version = "0.3.22"
kind = "target"
build_system = "meson"
dependencies = ["glib", "libxml2", "xz", "zstd"]
configure_args = ["-Dtests=false", "-Dgtkdoc=false", "-Dintrospection=false", "-Dstemmer=false", "-Dzstd=true"]

[source]
url = "https://github.com/hughsie/libxmlb/releases/download/{version}/libxmlb-{version}.tar.xz"
