format=1
name=webui-firewall
version=0.3.22
summary=WebUI adapter for firewall and intrusion protection
type=feature
architectures=x86_64,arm64
priority=84
requires=webui,firewall
after=firewall
services=
storage.count=0
