format=1
name=network
version=0.3.22
summary=Core IPv4 and IPv6 network configuration and diagnostics
type=feature
architectures=x86_64,arm64
priority=15
requires=system-core
after=
services=strataos-network
storage.count=1
storage.0.id=leases
storage.0.image=network.ext4
storage.0.mount=/var/lib/dhcpcd
storage.0.format=ext4
storage.0.initial_size_mib=16
storage.0.growth=inherit
storage.0.redundancy=inherit
storage.0.lifecycle=retain
storage.0.schema=1
storage.0.bind.count=0
