name = "libmnl"
version = "1.0.5"
kind = "target"
build_system = "autotools"
dependencies = []
configure_args = ["--disable-static", "--enable-shared"]

[source]
url = "https://www.netfilter.org/projects/libmnl/files/libmnl-{version}.tar.bz2"
sha256 = "274b9b919ef3152bfb3da3a13c950dd60d6e2bcd54230ffeca298d03b40d0525"
