name = "host-pycparser"
version = "2.23"
kind = "host"
build_system = "special"
special = "host-python-module"
dependencies = ["host-python"]
environment = ["PYTHON_MODULE=pycparser", "PYTHON_SOURCE=pycparser"]

[source]
url = "https://files.pythonhosted.org/packages/fe/cf/d2d3b9f5699fb1e4615c8e32ff220203e43b248e1dfcc6736ad9057731ca/pycparser-{version}.tar.gz"
sha256 = "78816d4f24add8f10a06d6f05b4d424ad9e96cfebf68a4ddc99c65c0720d00c2"
