format=1
name=diagnostics
version=0.3.22
summary=Optional interactive system diagnostics tools
type=feature
architectures=x86_64,arm64
priority=25
requires=system-core
after=
services=
storage.count=0
