name = "libpciaccess"
version = "0.18.1"
kind = "target"
build_system = "meson"
dependencies = ["zlib"]
configure_args = ["-Dzlib=enabled", "-Dlinux-rom-fallback=false"]

[source]
url = "https://www.x.org/releases/individual/lib/libpciaccess-{version}.tar.xz"
sha256 = "4af43444b38adb5545d0ed1c2ce46d9608cc47b31c2387fc5181656765a6fa76"
