format=1
name=system-core
version=0.3.22
summary=Minimum OpenRC, zsh and recovery-capable userspace
type=base
architectures=x86_64,arm64
priority=10
requires=
after=
services=strataos-storage,strataos-swap,strataos-logging,strataos-boot-ok
storage.count=1
storage.0.id=state
storage.0.image=state.ext4
storage.0.mount=/state
storage.0.format=ext4
storage.0.initial_size_mib=1024
storage.0.growth=inherit
storage.0.redundancy=inherit
storage.0.lifecycle=retain
storage.0.schema=1
storage.0.bind.count=5
storage.0.bind.0.source=home
storage.0.bind.0.target=/home
storage.0.bind.0.seed=copy
storage.0.bind.0.when=always
storage.0.bind.1.source=root
storage.0.bind.1.target=/root
storage.0.bind.1.seed=copy
storage.0.bind.1.when=always
storage.0.bind.2.source=dbus
storage.0.bind.2.target=/var/lib/dbus
storage.0.bind.2.seed=copy
storage.0.bind.2.when=always
storage.0.bind.3.source=log
storage.0.bind.3.target=/var/log
storage.0.bind.3.seed=copy
storage.0.bind.3.when=logging-persistent
storage.0.bind.4.source=etc-overlay
storage.0.bind.4.target=/etc
storage.0.bind.4.seed=overlay
storage.0.bind.4.when=always
