name = "libksba"
version = "1.6.7"
kind = "target"
build_system = "autotools"
dependencies = ["libgpg-error"]
configure_args = ["--disable-static", "--enable-shared", "--disable-doc"]
environment = ["GPGRT_CONFIG={sysroot}/usr/bin/gpgrt-config"]

[source]
url = "https://gnupg.org/ftp/gcrypt/libksba/libksba-{version}.tar.bz2"
sha256 = "cf72510b8ebb4eb6693eef765749d83677a03c79291a311040a5bfd79baab763"
