format=1
name=graphics
version=0.3.22
summary=Headless Wayland graphics, fonts and remote framebuffer runtime
type=feature
architectures=x86_64,arm64
priority=65
requires=system-core
after=
services=
storage.count=0
