name = "htop"
version = "3.5.2"
kind = "target"
build_system = "autotools"
dependencies = ["ncurses", "libcap"]
configure_args = [
    "--enable-unicode",
    "--enable-capabilities",
    "--disable-delayacct",
    "--disable-sensors",
    "--disable-hwloc",
    "--disable-backtrace",
    "--disable-demangling",
]

[source]
url = "https://github.com/htop-dev/htop/releases/download/{version}/htop-{version}.tar.xz"
sha256 = "225128e697c4a8c8a878fd0078c965ff8bd5fb24913bfc8473b8edbd50f843f8"
