name = "iputils"
version = "20250605"
kind = "target"
build_system = "meson"
dependencies = ["libcap"]
configure_args = [
    "-DUSE_CAP=true",
    "-DUSE_IDN=false",
    "-DUSE_GETTEXT=false",
    "-DBUILD_MANS=false",
    "-DBUILD_HTML_MANS=false",
    "-DSKIP_TESTS=true",
    "-DNO_SETCAP_OR_SUID=true",
]

[source]
url = "https://github.com/iputils/iputils/releases/download/{version}/iputils-{version}.tar.xz"
sha256 = "6f213700dbf96b5cc4499ca70cb15ecd69c09f405b06785bb4a1a10b572b6276"
