format=1
name=webui-openssh
version=0.3.22
summary=WebUI adapter for OpenSSH service controls
type=feature
architectures=x86_64,arm64
priority=83
requires=webui,openssh
after=openssh
services=
storage.count=0
