name = "libuv"
version = "1.52.1"
kind = "target"
build_system = "cmake"
dependencies = []
configure_args = ["-DBUILD_TESTING=OFF", "-DLIBUV_BUILD_SHARED=ON"]

[source]
url = "https://github.com/libuv/libuv/archive/refs/tags/v{version}.tar.gz"
sha256 = "478baf2599bfbc882c355288c9cb6f92e0e7dda435fa04031fa5b607cf3f414c"
