name = "llvm-libs"
version = "22.1.8"
kind = "target"
build_system = "special"
special = "llvm-libs"
dependencies = ["musl-runtime", "zlib", "zstd"]
configure_args = [
  "-DCMAKE_BUILD_TYPE=Release",
  "-DLLVM_INCLUDE_TESTS=OFF",
  "-DLLVM_INCLUDE_BENCHMARKS=OFF",
  "-DLLVM_INCLUDE_EXAMPLES=OFF",
  "-DLLVM_INCLUDE_DOCS=OFF",
  "-DLLVM_ENABLE_BINDINGS=OFF",
  "-DLLVM_ENABLE_LIBEDIT=OFF",
  "-DLLVM_ENABLE_LIBXML2=OFF",
  "-DLLVM_ENABLE_OCAMLDOC=OFF",
  "-DLLVM_ENABLE_Z3_SOLVER=OFF",
  "-DLLVM_BUILD_LLVM_DYLIB=ON",
  "-DLLVM_LINK_LLVM_DYLIB=ON",
  "-DLLVM_ENABLE_RTTI=ON",
  "-DLLVM_BUILD_TOOLS=OFF",
  "-DLLVM_BUILD_UTILS=OFF",
  "-DLLVM_INCLUDE_UTILS=OFF",
  "-DLLVM_BUILD_EXAMPLES=OFF",
  "-DLLVM_OPTIMIZED_TABLEGEN=ON",
  "-DLLVM_ENABLE_FFI=OFF",
  "-DLLVM_ENABLE_THREADS=ON",
  "-DLLVM_ENABLE_UNWIND_TABLES=OFF",
  "-DLLVM_ENABLE_EH=ON",
]
install_args = ["--strip"]

[source]
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-{version}/llvm-project-{version}.src.tar.xz"
