name = "npth"
version = "1.8"
kind = "target"
build_system = "autotools"
dependencies = []
configure_args = ["--disable-static", "--enable-shared"]

[source]
url = "https://gnupg.org/ftp/gcrypt/npth/npth-{version}.tar.bz2"
sha256 = "8bd24b4f23a3065d6e5b26e98aba9ce783ea4fd781069c1b35d149694e90ca3e"
