format=1
name=webui-network
version=0.3.22
summary=WebUI adapter for network configuration
type=feature
architectures=x86_64,arm64
priority=82
requires=webui,network
after=network
services=
storage.count=0
