PermitRootLogin yes
PasswordAuthentication yes
KbdInteractiveAuthentication no
PubkeyAuthentication yes
HostKey /var/lib/strataos/openssh/ssh_host_ed25519_key
HostKey /var/lib/strataos/openssh/ssh_host_rsa_key
UseDNS no
X11Forwarding no
AllowTcpForwarding yes
