name = "fuse3"
version = "3.17.2"
kind = "target"
build_system = "meson"
lto = "none"
dependencies = []
configure_args = ["-Dexamples=false", "-Dtests=false", "-Dudevrulesdir=/usr/lib/udev/rules.d", "-Duseroot=false"]

[source]
url = "https://github.com/libfuse/libfuse/releases/download/fuse-{version}/fuse-{version}.tar.gz"
