name = "noto-sans-cjk-sc"
version = "2.004"
kind = "target"
build_system = "special"
special = "font-file"
dependencies = []

[source]
url = "https://raw.githubusercontent.com/notofonts/noto-cjk/Sans2.004/Sans/SubsetOTF/SC/NotoSansSC-Regular.otf"
sha256 = "faa6c9df652116dde789d351359f3d7e5d2285a2b2a1f04a2d7244df706d5ea9"
archive = "file"
